### ISSUE TITLE
--format yml outputs invalid YAML

### ISSUE THREAD

**Issue by halfbyte** [appfolio/gemsurance#22]
Steps to Reproduce:
1. run `gemsurance --format yml` on a project that has vulnerabilities
2. run `ruby -e "require 'yaml';YAML.load_file('gemsurance_report.yml')"`

the yaml output format currently is broken, as it does not quote fields where quoting is necessary (most notably, `patched_versions` fields).

I'd also like to question the general idea of rendering out formats like YAML with erb, as this raises the risk of introducing format errors.

As output seems to be work in progress anyway, should I try to fix this in a PR? Or is this currently worked on anyway and therefore makes no sense for me to touch it?

Thanks for the great gem, btw!

**Comment by jonkessler** [comment]
Looks like this will be addressed with #27

**Comment by jonkessler** [comment]
Fixed by #27
