### ISSUE TITLE
Feature: show "age" of gems

### ISSUE THREAD

**Issue by thbar** [appfolio/gemsurance#9]
Thanks for your work on Gemsurance first!

One thing I would find fairly useful when investigating a freelancing project or my own apps would be to see the "age" of gems, aka how long ago the gem version was released. Not sure exactly of the details of how this could be implemented:
- maybe something in "Detailed Status" or "Status" ?
- maybe only show the age of the "Bundle Version" gem if marked "Out Of Date" ?

This is just an idea - but let me know what you think!

**Comment by thbar** [comment]
I took a first stab at implementing this (good enough for my needs, yet not in good shape for merging yet).

**Comment by jonkessler** [comment]
Also closing as stale. Let me know if you want it to be reopened.
